# Generated by Django 3.0.14 on 2023-02-07 03:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.IntegerField()),
                ('weight_in_kg', models.IntegerField()),
                ('length_in_cm', models.IntegerField()),
                ('height_in_cm', models.IntegerField()),
                ('width_in_cm', models.IntegerField()),
                ('name_of_shipper', models.CharField(max_length=500)),
                ('Recievers_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('Origin', django_countries.fields.CountryField(max_length=2)),
                ('Destination', django_countries.fields.CountryField(max_length=2)),
                ('Departure_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('pickup_date', models.DateField()),
            ],
        ),
    ]
